name: Deploy Chat App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Step 1: Set up MongoDB service container
    services:
       mongodb:
              image: mongo
              env:
                MONGO_INITDB_ROOT_USERNAME: test
                MONGO_INITDB_ROOT_PASSWORD: password
                MONGO_INITDB_DATABASE: test
              options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
              ports:
                - 27017:27017

    steps:
      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      # Step 4: Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      # Step 5: Create .env file for backend
      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "USER_INACTIVE=${{ secrets.USER_INACTIVE }}" >> .env
        working-directory: ./backend

      # Step 6: Debug .env file
      - name: Debug .env file
        run: cat .env
        working-directory: ./backend

      # Step 7: Wait for MongoDB to be ready
      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to be ready..."
          sleep 30  # Wait for 30 seconds
          timeout 60 bash -c 'until mongo --eval "db.runCommand(\"ping\").ok" mongodb://localhost:27017/chat-app; do sleep 1; done'
          echo "MongoDB is ready!"

      # Step 8: Debug MongoDB logs
      - name: Debug MongoDB logs
        run: |
          echo "Fetching MongoDB container logs..."
          docker logs $(docker ps -qf "name=mongodb")

      # Step 9: Start backend server
      - name: Start backend server
        run: |
          npm start
        working-directory: ./backend

      # Step 10: Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      # Step 11: Build Angular frontend
      - name: Build Angular frontend
        run: npm run build -- --configuration production
        working-directory: ./frontend

      # Step 12: Deploy frontend
      - name: Deploy frontend
        run: |
          # Add your deployment commands here
          # For example, if deploying to an S3 bucket:
          aws s3 sync ./frontend/dist/my-angular-app s3://your-s3-bucket-name --delete
        working-directory: ./frontend
