name: Deploy Chat App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x


      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend


      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "USER_INACTIVE=${{ secrets.USER_INACTIVE }}" >> .env
        working-directory: ./backend

      - name: Start backend server
        run: |
          npm start
        working-directory: ./backend


      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend


      - name: Build Angular frontend
        run: npm run build -- --configuration production
        working-directory: ./frontend


      - name: Deploy frontend
        run: |
          # Add your deployment commands here
          # For example, if deploying to an S3 bucket:
          aws s3 sync ./frontend/dist/my-angular-app s3://your-s3-bucket-name --delete
        working-directory: ./frontend
